<script src="/js/permutations.js"></script>
<script>
    function checkCycles(ans) {
        return (input) => {
            const ans_perm = new Permutation(ans);
            const in_perm = new Permutation().parseCycles(input);
            return in_perm.equals(ans_perm);
        }
    }
    function checkCyclesFromInput(input_id) {
        return (input) => {
            const ans = document.getElementById(input_id).value;
            const ans_perm = new Permutation().parseList(ans);
            const in_perm = new Permutation().parseCycles(input);
            return in_perm.equals(ans_perm);
        }
    }
    function checkShuffle(ans) {
        return (input) => {
            const ans_perm = new Permutation(ans);
            const in_perm = new Permutation().parseList(input);
            return in_perm.equals(ans_perm);
        }
    }
    function checkShuffleFromInput(input_id) {
        return (input) => {
            const ans = document.getElementById(input_id).value;
            const ans_perm = new Permutation().parseCycles(ans);
            const in_perm = new Permutation().parseList(input);
            return in_perm.equals(ans_perm);
        }
    }
    function checkProductofTranspositions(ans) {
        return (input) => {
            const ans_perm = new Permutation(ans);
            const cycles = readCycles(input);
            return cycles.every((c) => c.length == 2) && mulCycles(cycles).equals(ans_perm);
        }
    }
    function checkProductofTranspositionsFromInput(input_id) {
        return (input) => {
            const ans = document.getElementById(input_id).value;
            const ans_perm = new Permutation().parseCycles(ans);
            const cycles = readCycles(input);
            return cycles.every((c) => c.length == 2) && mulCycles(cycles).equals(ans_perm);
        }
    }
    function checkSignFromInput(input_id) {
        return (input) => {
            const cycles = document.getElementById(input_id).value;
            const ans = new Permutation().parseCycles(cycles).sign();
            return input == ans;
        }
    }
    function fillRandomShuffle(input_id, n) {
        const p = randomPermutation(n);
        document.getElementById(input_id).value = p.list;
    }
    function fillRandomCycles(input_id, n) {
        const cycles = randomPermutation(n).cycles;
        let str = "";
        for(cycle of cycles) { str += "(" + cycle + ")" }
        document.getElementById(input_id).value = str;
    }
</script>

# Exercises

1. Convert $2, 12, 3, 5, 4, 9, 8, 7, 6, 10, 1, 11$ to a product of cycles and draw the associated digraph.

```{julia}
#| echo: false
using QuizQuestions

scriptq("checkCycles([2, 12, 3, 5, 4, 9, 8, 7, 6, 10, 1, 11])", placeholder="Check your work")
```

2. Convert $(1,8,12)(2,3,6,7,9)(4,10,11)$ to a shuffle of $1,\dots,12$

```{julia}
#| echo: false
scriptq("checkShuffle([[1,8,12],[2,3,6,7,9],[4,10,11]])", placeholder="Check your work")
```

3. Show that $(12)(23)(34)(23)(12) = (14)$ by drawing the braid diagram.

4. Compute the sign of the permutations in 1. and 2.

::: {layout-ncol=2 .quiz-question-side-by-side}
```{julia}
#| echo: false
fillblankq("Problem 1: ____", ("1","-1"), 1)
```
```{julia}
#| echo: false
fillblankq("Problem 2: ____", ("1","-1"), 1)
```
:::

5. Write $(182635)$ as a product of transpositions.

```{julia}
#| echo: false
scriptq("checkProductofTranspositions([[1,8,2,6,3,5]])", placeholder="Check your work")
```

### Additional practice {.unnumbered}

::: panel-tabset

### Shuffle to Cycles

::: {.mx-2}
<label for="n-shuffle">n:</label>
<input type="number" id="n-shuffle" value="10">
<input type="button" id="shuffle-randomize" value="Randomize" onclick="fillRandomShuffle('shuffle-input', document.getElementById('n-shuffle').value)">
<br><br>
<input id="shuffle-input" class="form-control" placeholder="Shuffle">
:::

```{julia}
#| echo: false
scriptq("checkCyclesFromInput('shuffle-input')", placeholder="Check your work")
```

### Cycles to Shuffles

::: {.mx-2}
<label for="n-cycle">n:</label>
<input type="number" id="n-cycle" value="10">
<input type="button" id="cycle-randomize" value="Randomize" onclick="fillRandomCycles('cycle-input', document.getElementById('n-cycle').value)">
<br><br>
<input id="cycle-input" class="form-control" placeholder="Cycle decomposition">
:::

```{julia}
#| echo: false
scriptq("checkShuffleFromInput('cycle-input')", placeholder="Check your work")
```

### Sign
::: {.mx-2}
<label for="n-sign">n:</label>
<input type="number" id="n-sign" value="10">
<input type="button" id="sign-randomize" value="Randomize" onclick="fillRandomCycles('sign-input', document.getElementById('n-sign').value)">
<br><br>
<input id="sign-input" class="form-control" placeholder="Cycle decomposition">
:::

```{julia}
#| echo: false
scriptq("checkSignFromInput('sign-input')", placeholder="Check your work")
```

### Transpositions
::: {.mx-2}
<label for="n-transpositions">n:</label>
<input type="number" id="n-transpositions" value="10">
<input type="button" id="transpositions-randomize" value="Randomize" onclick="fillRandomCycles('transpositions-input', document.getElementById('n-transpositions').value)">
<br><br>
<input id="transpositions-input" class="form-control" placeholder="Cycle decomposition">
:::

```{julia}
#| echo: false
scriptq("checkProductofTranspositionsFromInput('transpositions-input')", placeholder="Check your work")
```

:::
