<script src="/js/ogf.js"></script>
<script>
    function fillRandomGeo(id, max_a, max_r) {
        let elt = document.getElementById(id);
        const a = randsigned(max_a);
        const r = randsigned(max_r);
        elt.setAttribute("a", a);
        elt.setAttribute("r", r);
        elt.innerText = "\\[" + geo(a, r) + "\\]";
        MathJax.typeset();
    }
    function checkGeo(geo_id) {
        return (input) => {
            const elt = document.getElementById(geo_id);
            const a = elt.getAttribute("a");
            const r = elt.getAttribute("r");
            return geoRE(a, r).test(input);
        }
    }
    function fillRandomSeq(id, max_a, max_an, max_r, max_rn) {
        let elt = document.getElementById(id);
        const [a, an, r, rn] = [ randsigned(max_a), randint(0, max_an), randsigned(max_r), randint(1, max_rn)];
        elt.setAttribute("a", a);
        elt.setAttribute("an", an);
        elt.setAttribute("r", r);
        elt.setAttribute("rn", rn);
        elt.innerText = "\\[" + seq(a, an, r, rn) + "\\dots \\]";
        MathJax.typeset();
    }
    function checkLT(seq_id) {
        return (input) => {
            const elt = document.getElementById(seq_id);
            const a = elt.getAttribute("a");
            const an = elt.getAttribute("an");
            return monomialRE(a, an).test(input);
        }
    }
    function checkRatio(seq_id) {
        return (input) => {
            const elt = document.getElementById(seq_id);
            const r = elt.getAttribute("r");
            const rn = elt.getAttribute("rn");
            return monomialRE(r, rn).test(input);
        }
    }
</script>

# Exercises

1. Given that $\displaystyle \frac{1}{1 - ax} = \sum_{n = 0}^\infty a^n x^n$, convert the following into summation notation (in terms of $x^n$ rather than $x^{n + k}$)
    a) $\dfrac{1}{1 - x} + \dfrac{1}{1 + x}$
    b) $\dfrac{x^3}{1 + 2x}$
    c) $\displaystyle \int_{0}^x \frac{1}{1 - t} \; dt = \log\left( \frac{1}{1 - x} \right)$
    (hint: take the antiderivative/integral term by term)
    d) $\dfrac{3}{2 - x}$
    (hint: convert to $\dfrac{a}{1 - bx}$)
    e) $\dfrac{1 + x}{1 - x^3}$
    (hint: split the fraction into two fractions)

::: {.callout-tip collapse="true"}
## Hints
a) Start with
$$
\frac{1}{1 - y} = \sum_{n = 0}^\infty y^n
$$
where maybe $y = x^3$ and we get $x^{3n}$ or $y = -x$ and we get $(-x)^n$.

b) If we multiply by $x^3$ and get $\sum a^n x^{n + 3}$ then subtract $3$ from $n$ everywhere to get $\sum a^{n - 3} x^n$. For the bottom of the summation, we would change from $n = 0$ to $n - 3 = 0$ or $n = 3$.

c) If we integrate $\sum x^n$ term by term, we get $\sum x^{n + 1}{n + 1}$.

d) Convert to $\dfrac{3/2}{1 - x/2}$.

e) You can write your answer as $\sum a_n x^n$ where $a_n = \dots$ (formula will depend on if $n = 3k, 3k + 1, 3k + 2$).
:::

2. Convert each sequence to a closed form generating function. Use the most obvious choice of form for the general term of the sequence. Sequences start at $n = 0$.
    a) $2, 2, 2, 2, 2, 2, \dots$
    b) $0, 1, 0, 1, 0, 1, \dots$
    c) $1, 0, 1, 0, 1, 0, \dots$
    d) $0, 1, 2, 3, 4, 5, \dots$ (hint: factor out an $x$ from $\sum nx^n$ so that the terms are $\frac{d}{dx} x^n$, then move the derivative operator outside the summation [but after the $x$ that was factored out])
    e) $1, 3, 5, 7, 9, 11, \dots$ (hint: use part d)

::: {.callout-tip collapse="true"}
## Hint
a) Write it first as $\sum 2x^n$ and factor out the $2$.
b) Write it first as $x + x^3 + x^5 + \dots$
c) Write it first as $1 + x^2 + x^4 + \dots$
d) $\displaystyle \frac{d}{dx} \frac{1}{1 - x} = \frac{1}{(1 - x)^2} = \sum nx^{n - 1}$
:::

3. Using the formulas from section @sec-sb-ogf-summary, find
    a) $\displaystyle \sum_{n = 0}^\infty \binom{n + 2}{2} x^n$
    b) $\displaystyle \sum_{n = 5}^\infty \binom{n - 1}{4} x^n$

::: {.callout-tip collapse="true"}
## Hint
a) Can be plugged into the formula directly
b) Look for the formula with $n - 1$ and then figure out how to choose the right $k$.
:::

4. Find the indicated coefficients.
    a) $[x^{10}] \dfrac{1}{1 + 2x}$
    b) $[x^{20}] \dfrac{1}{(1 - x)^7}$
    c) $[x^{20}] \dfrac{x^3}{(1 - x)^{10}}$
    d) $[x^{85}] \dfrac{2x^5}{1 - 3x^5}$
    (hint: if the sum is $\sum (*) x^{5n + 5}$ then the coefficient of $x^{85}$ occurs where $5n + 5 = 85$)

::: {.callout-tip collapse="true"}
## Hint
a) Use the formula $\sum (-2)^n x^n$ and take the coefficient of $x^{10}$
b) Use the formula from @sec-sb-ogf-summary.
c) First use the shift formula from @thm-shift-coefficient to write it as $[x^{17}] \dfrac{1}{(1 - x)^{10}}$.
d) The sum is $\sum 2 \cdot 3^n x^{5n + 5}$
:::

5. Write down a generating function for the number of ways to make change for $n$ dollars using $1, 5$ and $10$ dollar bills. (Hint: if we are receiving multiples of $\$5$ bills, then the generating function should be $x^0 + x^5 + x^{10} + \cdots$ where the weight function of a bill is its dolar value.)

::: {.callout-tip collapse="true"}
## Hint
If the options for $5 bills are $0, 1, 2, \dots$ then we have $1 + x^5 + x^{10} + x^{15} + \dots$ where the coefficient gives the number of choices (only 1 way to have $k$ bills of the same type) and the exponent gives the weight or how much it contributes.
You should get geometric series for each bill value.
:::

6. Repeat the previous problem but now suppose we are only allowed to give out a maximum of one $\$5$ bill.

::: {.callout-tip collapse="true"}
## Hint
Similar to problem 5. but now there are only $0$ or $1$ choices for the $5 bill. So $1 + x^5$ is the generating function for that denomination.
:::

::: {.content-visible when-format=html}
### Additional practice {.unnumbered}

::: panel-tabset

### Function to Series

<input type="button" id="geo-randomize" value="Randomize" onclick="fillRandomGeo('geo-text', 6, 6)" class="randomize_button flush" style="float: right">
Fill in the blank:
<p id="geo-text" a="2" r="3">\\[ \\frac{2}{1 - 3x} \\]</p>
is equal to $\displaystyle \sum_{n = 0}^\infty (\cdots) x^n$.

```{julia}
#| echo: false
using QuizQuestions

scriptq("checkGeo('geo-text')")
```

### Sequence to Function

<input type="button" id="seq-randomize" value="Randomize" onclick="fillRandomSeq('seq-text', 6, 3, 6, 3)" class="randomize_button" style="float: right">
What is the leading term and common ratio for the generating function whose coefficients are:
<p id="seq-text" a="2" r="-1" an="0" rn="1">\\[ 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, \\dots ? \\]</p>

::: {layout-ncol=2 .quiz-question-side-by-side}
```{julia}
#| echo: false
scriptq("checkLT('seq-text')", placeholder="Leading Term")
```
```{julia}
#| echo: false
scriptq("checkRatio('seq-text')", placeholder="Common Ratio")
```
:::

Hint: the leading term and common ratio might depend on $x$ after you turn the sequence into $a_0 + a_1x + a_2x^2 + a_3x^3 + \cdots$.
:::
:::

<details>
<summary>Solutions</summary>
1.
    a) $\displaystyle \sum_{n = 0}^\infty ((-1)^n + 1) x^n$
    b) $\displaystyle \sum_{n = 3}^\infty (-2)^{n  - 3}x^n$
    c) $\displaystyle \sum_{n = 1}^\infty \frac{x^n}{n}$
    d) $\displaystyle \sum_{n = 0}^\infty \frac{3}{2^{n + 1}} x^n$
    e) $\displaystyle \sum_{n = 0}^\infty a_n x^n$ where $a_n = 0$ if $n = 3k + 2$ and $a_n = 1$ otherwise (so the sequence $1, 1, 0, 1, 1, 0, 1, 1, 0, \dots$).
2.
    a) $\dfrac2{1 - x}$
    b) $\dfrac{x}{1 - x^2}$
    c) $\dfrac{1}{1 - x^2}$
    d) $\dfrac{x}{(1 - x)^2}$
    e) $\displaystyle \sum (2n + 1) x^n = 2\sum n x^n + \sum x^n = \frac{2}{(1 - x)^2} + \frac{1}{1 - x}$.
3.
    a) $\dfrac{1}{(1 - x)^3}$
    b) $\dfrac{x^5}{(1 - x)^5}$
4.
    a) $(-2)^{10}$
    b) $\dbinom{26}{6}$
    c) $\dbinom{26}{9}$
    d) $2 \cdot 3^{16}$
5. $\dfrac1{(1 - x)(1 - x^5)(1 - x^{10})}$
6. $\dfrac{1 + x^5}{(1 - x)(1 - x^{10})}$
</details>
